### PR TITLE
Multi version test

### PR DESCRIPTION
**Pull request by bandi13**
Fixes to run with different versions of WolfSSL.

Fixes to have different platforms run the test scripts.

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
Assigning back since CI tests listed as fail.

**Comment by bandi13** [comment]
retest this please

**Comment by bandi13** [comment]
retest this please

**Comment by douzzer** [comment]
retest this please.

**Comment by bandi13** [comment]
retest this please

**Comment by bandi13** [comment]
https://github.com/wolfSSL/wolfProvider/pull/14 superceeds this

**Pull request closed without merging**
